---
# task for setting up the database

- name: create a test database user
  postgresql_user: user=postgres password=postgres

- name: create test database
  postgresql_db: name=thinkdb owner=postgres